# Generated by Django 2.2.9 on 2020-06-04 22:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200120_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblepage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('fullsize_img', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('announce', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(verbose_name='titre')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock(verbose_name='contenu'))]))], null=True),
        ),
    ]
